### ISSUE TITLE
enchants

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [CLADevs/CLAAPI#1]
if i where to edit the SOLT_SWORD thing and make the number like 10 would it allow for sharp 10?

[link](https://github.com/CLADevs/CLAAPI/blob/master/src/CLADevs/enchantment/Enchantment.php#L33)

**Comment by PotatoeTrainYT** [comment]
personally, idk i havnt looked at the code much to understand but i think the 5 is the max level which can be enchanted using /enchant. so i guess if u edit the 5 it will upgrade it i guess

**Comment by xXNiceAssasinl0** [comment]
@PotatoeTrainYT I don’t think there max level xd

**Comment by xXNiceAssasinl0** [comment]
@XoticRealmsOwnerandDev Enchants are max ;) it’s infinity
